server:
  port: 8088

# KAFKA
spring:
  kafka:
    bootstrap-servers: omnibus-01.srvs.cloudkafka.com:9094,omnibus-02.srvs.cloudkafka.com:9094,omnibus-03.srvs.cloudkafka.com:9094
    properties.security.protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username=v13jy9uz password="4YmXQCOBIy4c7r2qVr4wlM5KPEBifPgw";
    consumer:
      group-id: v13jy9uz-consumers
      auto-offset-reset: latest
      properties.spring.json.trusted.packages: sample.kafka
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

cloudkarafka:
  topic: v13jy9uz-default